### ISSUE TITLE
Will_paginate doesn't work with rails 2.3 upgraded with Bundler using gem

### ISSUE THREAD

**Issue by Ravenna** [mislav/will_paginate#203]
So I am not 100% sure on this but wanted to make a note anyway..  

The error I was seeing was: “undefined method `paginate’” on both arrays and classes.

I have a rails 2.3 app, which was updated to bundler.  Instead of loading the app through plugin, I loaded it through the Gemfile.  By using the first items listed in your troubleshooting wiki:

> > defined? WillPaginate
> > ActiveRecord::Base.respond_to? :paginate

I was able to determine that will_paginate was not even being loaded.  I had all the gems installed, the bundle looked good from all available signs. 

Seemed weird to me, I was able to resolve it by loading an old version of the plugin into my plugins folder and things worked great.
